# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
    build:
        docker:
            - image: circleci/golang:1.11

        working_directory: /go/src/github.com/opethe1st/GoJson
        steps:
            - checkout
            - run:
                  name: "Create a temp directory for artifacts"
                  command: |
                      mkdir -p /tmp/artifacts
            - run: go get -v -t -d ./...
            - run: go vet ./...
            - run: gofmt -d . > /tmp/artifacts/fmt-diff # shows the diff
            - run: "[ ! -s /tmp/artifacts/fmt-diff ]" # if this file exists and is not empty, status code is 1
            - run: go test -v ./...
            - run:
                command: |
                    cd src/json
                    go test -coverprofile=c.out
                    go tool cover -html=c.out -o coverage.html
                    mv coverage.html /tmp/artifacts
            - store_artifacts:
                path: /tmp/artifacts
